title: "Your Name"
description: "Machine Learning Engineer • Bengaluru, India"
url: "https://<your-username>.github.io"
baseurl: ""

# Use Minimal Mistakes as a remote theme (works on GitHub Pages)
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

# Author/sidebar profile
author:
  name: "Your Name"
  avatar: "/assets/img/avatar.jpg"
  bio: "Hi! I build LLM and NLP systems and write about privacy & fairness. Always up to chat or collaborate."
  location: "Bengaluru, India"
  email: "you@example.com"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/yourhandle"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/<your-username>"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:you@example.com"

# Layout defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true

# Navigation (top bar)
include: ["_pages"]
