title: "Neha Mittal"
description: "Machine Learning Engineer • Bengaluru, India"
url: "https://nxob.github.io"
baseurl: "/nehamittal.github.io"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-remote-theme

author:
  name: "Neha Mittal"
  avatar: "/assets/img/avatar.jpg"
  bio: "Hi! I build LLM and NLP systems and write about privacy & fairness."
  location: "Bengaluru, India"
  email: "you@example.com"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/your-handle"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/nxob"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:you@example.com"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true

include: ["_pages"]

theme: jekyll-theme-minimal
